name: CI Pipeline

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    # Run Pylint
    - name: Run Pylint with reviewdog
      uses: reviewdog/action-pylint@v1
      with:
        pylint_flags: "--output-format=text test_project_user_service/**/*.py"
        level: error
        reporter: github-pr-review
        filter_mode: file
